export const FETCH_PRODUCT_REQUEST='FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS='FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILED='FETCH_PRODUCT_FAILED'

export const GET_SINGLEPRODUCT_ID='GET_SINGLEPRODUCT_ID'

export const FETCH_TYPE_REQUEST='FETCH_TYPE_REQUEST'
export const FETCH_TYPE_SUCCESS='FETCH_TYPE_SUCCESS'
export const FETCH_TYPE_FAILED='FETCH_TYPE_FAILED'

export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_FROM_CART='REMOVE_FROM_CART'